"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Registering a unhandledRejection handler that throws the provided exception ensures that code
 * that has an unhandled rejection fails a test case and does not let failing code continue unnoticed.
 * This is the warning this code replaces: UnhandledPromiseRejectionWarning: Unhandled promise
 * rejection. This error originated either by throwing inside of an async function without a catch block,
 * or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 */
function crashOnUnhandledRejections() {
    process.on('unhandledRejection', unhandledRejection => {
        if (unhandledRejection instanceof Error) {
            const error = unhandledRejection;
            console.error('unhandledRejection called. There is likely a missing "await" in this call stack: ' + error.stack);
        }
        else {
            const rejectionDescription = unhandledRejection ? typeof unhandledRejection + ' ' + unhandledRejection.toString() : 'undefined';
            console.error(`unhandledRejection called. There is likely a missing "await" where ${rejectionDescription} was thrown.`);
        }
        throw unhandledRejection;
    });
}
exports.crashOnUnhandledRejections = crashOnUnhandledRejections;
//# sourceMappingURL=unhandledRejectionHandler.js.map